#!/usr/bin/env php
<?php

require_once __DIR__ . '/lib/vendor/autoload.php';
require_once __DIR__ . '/WordpressPluginGenerator.php';

use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new WordpressPluginGenerator());
try {
    $app->run();
} catch (Exception $e) {
    echo $e->getMessage();
}